/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/girl.gltf -o src/components/CharacterSoldier.jsx -r public -k 
*/

import React, {useEffect, useMemo, useRef} from 'react'
import {useAnimations, useGLTF} from '@react-three/drei'
import {SkeletonUtils} from "three-stdlib";
import {LoopOnce} from "three";
import {useGraph} from "@react-three/fiber";

export function CharacterSoldier({
                                     color = "black",
                                     animation = "Idle",
                                     weapon = "AK",
                                     ...props
                                 }) {
    const group = useRef()
    const {scene, materials, animations} = useGLTF('/models/girl.glb')
    const {actions} = useAnimations(animations, group)
    // Skinned meshes cannot be re-used in threejs without cloning them
    const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
    // useGraph creates two flat object collections for nodes and materials
    const {nodes} = useGraph(clone)

    if (actions["Death"]) {
        actions["Death"].loop = LoopOnce
        actions["Death"].clampWhenFinished = true
    }

    useEffect(() => {
        actions[animation].reset().fadeIn(0.2).play()
        return () => actions[animation]?.fadeOut(0.2)
    }, [animation])


    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="CharacterArmature">
                    <primitive object={nodes.Root}/>
                    <group name="Sketchfab_model" position={[-0.001, -0.029, 0]} rotation={[-Math.PI / 2, 0, 0]}
                           scale={0.3}/>
                    <primitive object={nodes.neutral_bone}/>
                    <group name="AK" position={[-0.358, 0.725, 0.516]} rotation={[-1.141, -0.844, -1.663]}
                           scale={0.418}>
                        <mesh name="Cube276" geometry={nodes.Cube276.geometry} material={materials.Grey}/>
                        <mesh name="Cube276_1" geometry={nodes.Cube276_1.geometry} material={materials.Grey2}/>
                        <mesh name="Cube276_2" geometry={nodes.Cube276_2.geometry} material={materials.Wood}/>
                        <mesh name="Cube276_3" geometry={nodes.Cube276_3.geometry} material={materials.DarkGrey}/>
                    </group>
                    <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['nnj07_und_mat.002']}
                          position={[-0.001, -0.029, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}/>
                    <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials['002_bmp.002']}
                          position={[-0.001, -0.029, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}/>
                    <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['004_bmp.004']}
                          position={[-0.001, -0.029, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.3}/>
                    <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry}
                                 material={materials['body_mat.003']} skeleton={nodes.Object_10.skeleton}/>
                    <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry}
                                 material={materials['face_mat.002_NONE.003']} skeleton={nodes.Object_11.skeleton}/>
                    <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry}
                                 material={materials['hair_mat.002']} skeleton={nodes.Object_12.skeleton}/>
                    <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry}
                                 material={materials['swimsuit_mat.001_swim00_00.png.002']}
                                 skeleton={nodes.Object_13.skeleton}/>
                    <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry}
                                 material={materials['swimsuit_mat.002']} skeleton={nodes.Object_14.skeleton}/>
                    <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry}
                                 material={materials['body_mat.001_pl07_skin.png.002']}
                                 skeleton={nodes.Object_15.skeleton}/>
                    <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry}
                                 material={materials['face_mat.002']} skeleton={nodes.Object_16.skeleton}/>
                    <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry}
                                 material={materials['nnj07_up_mat.002']} skeleton={nodes.Object_18.skeleton}/>
                    <skinnedMesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials['003_bmp.002']}
                                 skeleton={nodes.Object_3.skeleton}/>
                    <skinnedMesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['004_bmp.003']}
                                 skeleton={nodes.Object_5.skeleton}/>
                    <skinnedMesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['005_bmp.002']}
                                 skeleton={nodes.Object_6.skeleton}/>
                    <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['006_bmp.002']}
                                 skeleton={nodes.Object_7.skeleton}/>
                    <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry}
                                 material={materials['Material__57.002']} skeleton={nodes.Object_8.skeleton}/>
                    <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['body_mat.004']}
                                 skeleton={nodes.Object_9.skeleton}/>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/girl.glb')
